model:
    py: /home/yhcao6/resnet_seg/train_resnet.py
snapshot_interval: 4000
load_from: /home/yhcao6/resnet_seg/params.h5
work_dir: work_dir
max_iter: 20000
init_missing: True 

# execute flow train and flow val alternately
epoch:
  - flow: train
    policy: iterate
    args:
      iter_num: 1000    # total iter_num x batch_size samples
      log_vars: [loss_fusion, loss_res05, loss_res075, loss_res1]
      log_interval: 20

flows:
  - train:
      spec:
        inputs: [data, label, label_weight]
        outputs: [loss_fusion, loss_res05, loss_res075, loss_res1]
        losses: [loss_fusion, loss_res05, loss_res075, loss_res1]
      batch_size: 5
      inner_iter: 2
      devices: gpu(0:5) # other options: gpu(0) or gpu(0: 2)
      learn:
        lr: 2.5e-4
        weight_decay: 0.0005
        # lr_policy: fixed
        lr_policy: poly(20000, 0.9)
        updater:
          type: sgd
          momentum: 0.9
      feeder:
        pipeline:
          - expr: "data, label, label_weight = seg_reader()"
            attr:
              source: /home/yhcao6/train_aug.txt
              data_root: /home/yhcao6/VOC_arg
              label_root: /home/yhcao6/VOC_arg
              is_shuffle: 1
              is_mirror: 1

loggers:
  - type: local
  - type: pavi
    args:
      url: http://pavi.parrotsdnn.org/log
      username: yhcao6 
      password: Cyh1996418 

extra:
  custom_paths: ['/home/yhcao6/resnet_seg', '/home/yhcao6']
  custom_modules: ['seg_reader', 'ext_layer']
# record_best:
#   val_flow: val
#   field: accuracy
#   factor: -1
